site_name: "QField API Documentation"

theme:
  name: material

plugins:
  - search
  - mkdoxy:
      projects:
        QField:
          src-dirs: "./src/core ./src/core/utils ./src/core/positioning ./src/qml"
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.cpp *.h* *.qml"
            FILTER_PATTERNS: "*.qml=doxyqml"
            RECURSIVE: False
            EXTENSION_MAPPING: "qml=C++"

nav:
  - Home: index.md
  - Groups:
      - All: QField/annotated.md
      - Core: QField/group__core.md
      - QML: QField/group__qml.md
